# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=40)),
                ('primer_apellido', models.CharField(max_length=40)),
                ('segundo_apellido', models.CharField(blank=True, max_length=40)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('institucion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'ordering': ['primer_apellido'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=4)),
                ('titulo', models.CharField(max_length=250)),
                ('area_tematica', models.CharField(choices=[('1', 'Currículo médico'), ('2', 'Educación en ciencias básicas'), ('3', 'Formación clínica'), ('4', 'Desarrollo del profesionalismo y del comportamiento ético'), ('5', 'Educación orientada por competencias'), ('6', 'Procesos sociocognitivos y diseños instruccionales para el aprendizaje'), ('7', 'Internado médico de pregrado y Servicio Social'), ('8', 'Simulación en la formación de médicos'), ('9', 'Tecnologías de la información y las telecomunicaciones en la educación médica'), ('10', 'Evaluación del aprendizaje'), ('11', 'Alumnos como actores del proceso formativo'), ('12', 'Docentes como actores del proceso formativo'), ('13', 'Posgrado'), ('14', 'Desarrollo profesional continuado'), ('15', 'Planeación, gestión, operación y evaluación, calidad y excelencia de las facultades y escuelas de medicina'), ('16', 'Internacionaliación de la educación médica'), ('17', 'Innovación y liderazco en educación médica')], max_length=2)),
                ('autores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribucion.Autor')),
            ],
        ),
    ]
