# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-29 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribucion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='autores',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='autores',
            field=models.ManyToManyField(to='contribucion.Autor'),
        ),
    ]
