# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribucion', '0002_auto_20160629_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='autores',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='autores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contribucion.Autor'),
            preserve_default=False,
        ),
    ]
