# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-01 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribucion', '0004_auto_20160630_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo_Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.ManyToManyField(to='contribucion.Autor')),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='autores',
        ),
        migrations.AddField(
            model_name='trabajo_autor',
            name='trabajos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribucion.Trabajo'),
        ),
    ]
